#!/bin/bash
# Docker Volume Inspection Guide
# Run these commands on your laptop to identify volumes used by containers

echo "========================================="
echo "DOCKER VOLUME INSPECTION COMMANDS"
echo "========================================="
echo ""

echo "1. LIST ALL VOLUMES"
echo "-------------------"
echo "Command: docker volume ls"
echo ""
docker volume ls 2>/dev/null || echo "Run this on your laptop where Docker is installed"
echo ""

echo "2. FIND VOLUMES USED BY RUNNING CONTAINERS"
echo "-------------------------------------------"
echo "Command: docker ps --format 'table {{.Names}}\t{{.Mounts}}'"
echo ""
docker ps --format 'table {{.Names}}\t{{.Mounts}}' 2>/dev/null || echo "Run this on your laptop"
echo ""

echo "3. INSPECT SPECIFIC CONTAINER (shows all volumes)"
echo "--------------------------------------------------"
echo "Command: docker inspect <container_name> | grep -A 10 'Mounts'"
echo "Example: docker inspect openo-mariadb-dev | grep -A 10 'Mounts'"
echo ""

echo "4. DOCKER COMPOSE VOLUMES (for this project)"
echo "----------------------------------------------"
echo "Command: docker-compose ps -q | xargs docker inspect --format '{{.Name}}: {{range .Mounts}}{{.Name}} {{end}}'"
echo ""

echo "5. FIND VOLUME BY IMAGE NAME"
echo "-----------------------------"
echo "Command: docker ps --filter ancestor=<image_name> --format '{{.Names}}' | xargs -I {} docker inspect {} --format '{{.Name}}: {{range .Mounts}}{{.Source}} -> {{.Destination}} {{end}}'"
echo ""

echo "6. GET VOLUME SIZE"
echo "------------------"
echo "Command: docker system df -v"
echo ""
docker system df -v 2>/dev/null || echo "Run this on your laptop"
echo ""

echo "7. DETAILED VOLUME INSPECTION"
echo "------------------------------"
echo "Command: docker volume inspect <volume_name>"
echo "Example: docker volume inspect openo-emr_mariadb-files"
echo ""

echo "========================================="
echo "OPENO EMR SPECIFIC VOLUMES"
echo "========================================="
echo ""
echo "Based on your docker-compose.yml configuration:"
echo ""
echo "Container: openo-tomcat-dev (open-o service)"
echo "  └─ m2-volume -> /root/.m2 (Maven cache, ~1-2GB)"
echo "  └─ ../workspace -> /workspace (source code, bind mount)"
echo "  └─ db_data -> /db-data (database seed data, bind mount)"
echo ""
echo "Container: openo-mariadb-dev (db service)"
echo "  └─ mariadb-files -> /var/lib/mysql (DATABASE, ~11GB)"
echo ""
echo "IMPORTANT: The 11GB volume is 'mariadb-files'"
echo "  - Full name likely: openo-emr_mariadb-files"
echo "  - Contains: All database tables and patient data"
echo "  - Priority: HIGH - This is what you want to migrate!"
echo ""
